# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-10 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cowhite_cms', '0002_auto_20180617_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='title_on_image',
            field=models.CharField(blank=True, help_text='Optional. Defaults to page title.', max_length=255, null=True),
        ),
    ]
